BOX_IMAGE="ubuntu/bionic64"
Vagrant.configure("2") do |config|

	config.vm.define "master" do |subconfig|
		subconfig.vm.box = BOX_IMAGE
		subconfig.vm.hostname = "a.host.name"
		subconfig.vm.network :private_network, ip: "10.0.0.10"
		subconfig.vm.synced_folder "data/", "/data"
  		subconfig.vm.provision :shell, path: "bootstrap.sh"
  		subconfig.vm.network :forwarded_port, guest: 80, host: 4567
	end

	config.vm.define "node" do |subconfig|
		subconfig.vm.box = BOX_IMAGE
		subconfig.vm.hostname = "b.host.name"
		subconfig.vm.network :private_network, ip: "10.0.0.20"
	end

config.vm.provision "shell", inline: <<-SHELL
  apt-get update && apt-get install -y avahi-daemon libnss-mdns
SHELL

end
